export const AUTHENTICATE_USER_REQUEST = 'AUTHENTICATE_USER_REQUEST';
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';
export const AUTHENTICATE_USER_FAILURE = 'AUTHENTICATE_USER_FAILURE';

export const USER_ROLES_REQUEST = 'USER_ROLES_REQUEST';
export const USER_ROLES_SUCCESS = 'USER_ROLES_SUCCESS';
export const USER_ROLES_FAILURE = 'USER_ROLES_FAILURE';

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';

/**
 * USER MANEGEMENT actions
 */
export const ON_VALIDATE_INPUT = 'ON_VALIDATE_INPUT';
export const SUCCESS_GET_USER_INFO = 'SUCCESS_GET_USER_INFO';
export const SUCCESS_GET_ERROR = 'SUCCESS_GET_ERROR';
export const SUCCESS_BLOCK_UNBLOCK = 'SUCCESS_BLOCK_UNBLOCK';
export const SUCCESS_HIDE_ERRORS = 'SUCCESS_HIDE_ERRORS';
export const SUCCESS_CLEAR_FIELDS = 'SUCCESS_CLEAR_FIELDS';
export const SHOW_SUCCESS_MESSAGE = 'SHOW_SUCCESS_MESSAGE';
export const CHANGE_USER_CREDENTIALS = 'CHANGE_USER_CREDENTIALS';

export const LOGOUT_USER = 'LOGOUT_USER';
