export const FETCH_SMS_EVENTS_REQUEST = 'FETCH_SMS_EVENTS_REQUEST';
export const FETCH_SMS_EVENTS_SUCCESS = 'FETCH_SMS_EVENTS_SUCCESS';
export const FETCH_SMS_EVENTS_FAILURE = 'FETCH_SMS_EVENTS_FAILURE';

export const FETCH_EMAIL_EVENTS_REQUEST = 'FETCH_EMAIL_EVENTS_REQUEST';
export const FETCH_EMAIL_EVENTS_SUCCESS = 'FETCH_EMAIL_EVENTS_SUCCESS';
export const FETCH_EMAIL_EVENTS_FAILURE = 'FETCH_EMAIL_EVENTS_FAILURE';

export const FETCH_WHATS_APP_EVENTS_REQUEST = 'FETCH_WHATS_APP_EVENTS_REQUEST';
export const FETCH_WHATS_APP_EVENTS_SUCCESS = 'FETCH_WHATS_APP_EVENTS_SUCCESS';
export const FETCH_WHATS_APP_EVENTS_FAILURE = 'FETCH_WHATS_APP_EVENTS_FAILURE';

export const FETCH_PUSH_NOTIFICATION_EVENTS_REQUEST =
  'FETCH_PUSH_NOTIFICATION_EVENTS_REQUEST';
export const FETCH_PUSH_NOTIFICATION_EVENTS_SUCCESS =
  'FETCH_PUSH_NOTIFICATION_EVENTS_SUCCESS';
export const FETCH_PUSH_NOTIFICATION_EVENTS_FAILURE =
  'FETCH_PUSH_NOTIFICATION_EVENTS_FAILURE';

export const FETCH_EMAIL_EVENT_REQUEST = 'FETCH_EMAIL_EVENT_REQUEST';
export const FETCH_EMAIL_EVENT_SUCCESS = 'FETCH_EMAIL_EVENT_SUCCESS';
export const FETCH_EMAIL_EVENT_FAILURE = 'FETCH_EMAIL_EVENT_FAILURE';

export const FETCH_EMAIL_ID_TEMPLATES_REQUEST =
  'FETCH_EMAIL_ID_TEMPLATES_REQUEST';
export const FETCH_EMAIL_ID_TEMPLATES_SUCCESS =
  'FETCH_EMAIL_ID_TEMPLATES_SUCCESS';
export const FETCH_EMAIL_ID_TEMPLATES_FAILURE =
  'FETCH_EMAIL_ID_TEMPLATES_FAILURE';

export const FETCH_SMS_TEMPLATES_SUCCESS = 'FETCH_SMS_TEMPLATES_SUCCESS';
export const FETCH_SMS_TEMPLATES_FAILURE = 'FETCH_SMS_TEMPLATES_FAILURE';
export const FETCH_WHATSAPP_TEMPLATES_SUCCESS =
  'FETCH_WHATSAPP_TEMPLATES_SUCCESS';
export const FETCH_WHATSAPP_TEMPLATES_FAILURE =
  'FETCH_WHATSAPP_TEMPLATES_FAILURE';
export const FETCH_PUSH_NOTIFICATION_TEMPLATES_SUCCESS =
  'FETCH_PUSH_NOTIFICATION_TEMPLATES_SUCCESS';
export const FETCH_PUSH_NOTIFICATION_TEMPLATES_FAILURE =
  'FETCH_PUSH_NOTIFICATION_TEMPLATES_FAILURE';

export const SWITCH_CURRENT_EVENT_LOADING = 'SWITCH_CURRENT_EVENT_LOADING';
export const CLEAR_EMAIL_EVENT = 'CLEAR_EMAIL_EVENT';

export const UPDATE_SMS_EVENTS_REQUEST = 'UPDATE_SMS_EVENTS_REQUEST';
export const UPDATE_SMS_EVENTS_SUCCESS = 'UPDATE_SMS_EVENTS_SUCCESS';
export const UPDATE_SMS_EVENTS_FAILURE = 'UPDATE_SMS_EVENTS_FAILURE';

export const ADD_EVENT_TO_CURRENT_EVENT = 'ADD_EVENT_TO_CURRENT_EVENT';
export const REMOVE_EVENT_TO_CURRENT_EVENT = 'REMOVE_EVENT_TO_CURRENT_EVENT';

export const TOGGLE_ACTION_DATA_REQUEST = 'TOGGLE_ACTION_DATA_REQUEST';
export const TOGGLE_ACTION_DATA_SUCCESS = 'TOGGLE_ACTION_DATA_SUCCESS';
export const TOGGLE_ACTION_DATA_FAILURE = 'TOGGLE_ACTION_DATA_FAILURE';

export const PREVIEW_EMAIL_EVENTS_REQUEST = 'PREVIEW_EMAIL_EVENTS_REQUEST';
export const PREVIEW_EMAIL_EVENTS_SUCCESS = 'PREVIEW_EMAIL_EVENTS_SUCCESS';
export const PREVIEW_EMAIL_EVENTS_FAILURE = 'PREVIEW_EMAIL_EVENTS_FAILURE';

export const PREVIEW_SMS_EVENTS_REQUEST = 'PREVIEW_SMS_EVENTS_REQUEST';
export const PREVIEW_SMS_EVENTS_SUCCESS = 'PREVIEW_SMS_EVENTS_SUCCESS';
export const PREVIEW_SMS_EVENTS_FAILURE = 'PREVIEW_SMS_EVENTS_FAILURE';

export const PREVIEW_PUSH_NOTIFICATION_EVENTS_REQUEST =
  'PREVIEW_PUSH_NOTIFICATION_EVENTS_REQUEST';
export const PREVIEW_PUSH_NOTIFICATION_EVENTS_SUCCESS =
  'PREVIEW_PUSH_NOTIFICATION_EVENTS_SUCCESS';
export const PREVIEW_PUSH_NOTIFICATION_EVENTS_FAILURE =
  'PREVIEW_PUSH_NOTIFICATION_EVENTS_FAILURE';

export const PREVIEW_EMAIL_TEMPLATE_REQUEST = 'PREVIEW_EMAIL_TEMPLATE_REQUEST';
export const PREVIEW_EMAIL_TEMPLATE_SUCCESS = 'PREVIEW_EMAIL_TEMPLATE_SUCCESS';
export const PREVIEW_EMAIL_TEMPLATE_FAILURE = 'PREVIEW_EMAIL_TEMPLATE_FAILURE';

export const UPDATE_EMAIL_EVENTS_REQUEST = 'UPDATE_EMAIL_EVENTS_REQUEST';
export const UPDATE_EMAIL_EVENTS_SUCCESS = 'UPDATE_EMAIL_EVENTS_SUCCESS';
export const UPDATE_EMAIL_EVENTS_FAILURE = 'UPDATE_EMAIL_EVENTS_FAILURE';

export const UPDATE_WHATS_APP_EVENTS_REQUEST =
  'UPDATE_WHATS_APP_EVENTS_REQUEST';
export const UPDATE_WHATS_APP_EVENTS_SUCCESS =
  'UPDATE_WHATS_APP_EVENTS_SUCCESS';
export const UPDATE_WHATS_APP_EVENTS_FAILURE =
  'UPDATE_WHATS_APP_EVENTS_FAILURE';

export const UPDATE_PUSH_NOTIFICATION_EVENTS_REQUEST =
  'UPDATE_PUSH_NOTIFICATION_EVENTS_REQUEST';
export const UPDATE_PUSH_NOTIFICATION_EVENTS_SUCCESS =
  'UPDATE_PUSH_NOTIFICATION_EVENTS_SUCCESS';
export const UPDATE_PUSH_NOTIFICATION_EVENTS_FAILURE =
  'UPDATE_PUSH_NOTIFICATION_EVENTS_FAILURE';

/* Raven APP */

// FETCH Root Nodes Constant
export const CREATE_RAVEN_NODE_REQUEST = 'CREATE_RAVEN_NODE_REQUEST';
export const CREATE_RAVEN_NODE_SUCCESS = 'CREATE_RAVEN_NODE_SUCCESS';
export const CREATE_RAVEN_NODE_FAILURE = 'CREATE_RAVEN_NODE_FAILURE';

export const FETCH_RAVEN_ROOT_NODES_REQUEST = 'FETCH_RAVEN_ROOT_NODES_REQUEST';
export const FETCH_RAVEN_ROOT_NODES_SUCCESS = 'FETCH_RAVEN_ROOT_NODES_SUCCESS';
export const FETCH_RAVEN_ROOT_NODES_FAILURE = 'FETCH_RAVEN_ROOT_NODES_FAILURE';

export const ASSIGN_ROOT_NODE_DETAILS = 'ASSIGN_ROOT_NODE_DETAILS';

export const UPDATE_RAVEN_NODE_REQUEST = 'UPDATE_RAVEN_NODE_REQUEST';
export const UPDATE_RAVEN_NODE_SUCCESS = 'UPDATE_RAVEN_NODE_SUCCESS';
export const UPDATE_RAVEN_NODE_FAILURE = 'UPDATE_RAVEN_NODE_FAILURE';

export const UPDATE_RAVEN_NODE_RANK_REQUEST = 'UPDATE_RAVEN_NODE_RANK_REQUEST';
export const UPDATE_RAVEN_NODE_RANK_SUCCESS = 'UPDATE_RAVEN_NODE_RANK_SUCCESS';
export const UPDATE_RAVEN_NODE_RANK_FAILURE = 'UPDATE_RAVEN_NODE_RANK_FAILURE';
export const UPDATE_CHANGE_NODE_RANK = 'UPDATE_CHANGE_NODE_RANK';
export const SET_CURRENT_NODE_KEY = 'SET_CURRENT_NODE_KEY';

export const FETCH_LINKED_RAVEN_NODE_REQUEST =
  'FETCH_LINKED_RAVEN_NODE_REQUEST';
export const FETCH_LINKED_RAVEN_NODE_SUCCESS =
  'FETCH_LINKED_RAVEN_NODE_SUCCESS';
export const FETCH_LINKED_RAVEN_NODE_FAILURE =
  'FETCH_LINKED_RAVEN_NODE_FAILURE';

// ADD Root Nodes Constants
export const ADD_RAVEN_NODE_REQUEST = 'ADD_RAVEN_NODE_REQUEST';
export const ADD_RAVEN_NODE_SUCCESS = 'ADD_RAVEN_NODE_SUCCESS';
export const ADD_RAVEN_NODE_FAILURE = 'ADD_RAVEN_NODE_FAILURE';

// ADD Root Nodes Constants
export const ADD_RAVEN_NODE_ACTION_REQUEST = 'ADD_RAVEN_NODE_ACTION_REQUEST';
export const ADD_RAVEN_NODE_ACTION_SUCCESS = 'ADD_RAVEN_NODE_ACTION_SUCCESS';
export const ADD_RAVEN_NODE_ACTION_FAILURE = 'ADD_RAVEN_NODE_ACTION_FAILURE';

// ADD Root Nodes Constants
export const CHANGE_RAVEN_NODE_ACTION_REQUEST =
  'CHANGE_RAVEN_NODE_ACTION_REQUEST';
export const CHANGE_RAVEN_NODE_ACTION_SUCCESS =
  'CHANGE_RAVEN_NODE_ACTION_SUCCESS';
export const CHANGE_RAVEN_NODE_ACTION_FAILURE =
  'CHANGE_RAVEN_NODE_ACTION_FAILURE';

export const FETCH_RAVEN_INACTIVE_NODE_LINKS_REQUEST =
  'FETCH_RAVEN_INACTIVE_NODE_LINKS_REQUEST';
export const FETCH_RAVEN_INACTIVE_NODE_LINKS_SUCCESS =
  'FETCH_RAVEN_INACTIVE_NODE_LINKS_SUCCESS';
export const FETCH_RAVEN_INACTIVE_NODE_LINKS_FAILURE =
  'FETCH_RAVEN_INACTIVE_NODE_LINKS_FAILURE';

// FETCH Nodes Constants
export const FETCH_RAVEN_NODES_REQUEST = 'FETCH_RAVEN_NODES_REQUEST';
export const FETCH_RAVEN_NODES_SUCCESS = 'FETCH_RAVEN_NODES_SUCCESS';
export const FETCH_RAVEN_NODES_FAILURE = 'FETCH_RAVEN_NODES_FAILURE';

// FETCH Root Actions Constants
export const FETCH_RAVEN_ACTIONS_NODES_REQUEST =
  'FETCH_RAVEN_ACTIONS_NODES_REQUEST';
export const FETCH_RAVEN_ACTIONS_NODES_SUCCESS =
  'FETCH_RAVEN_ACTIONS_NODES_SUCCESS';
export const FETCH_RAVEN_ACTIONS_NODES_FAILURE =
  'FETCH_RAVEN_ACTIONS_NODES_FAILURE';

// FETCH Root Nodes Constants
export const SEND_RAVEN_NODE_LINK_REQUEST = 'SEND_RAVEN_NODE_LINK_REQUEST';
export const SEND_RAVEN_NODE_LINK_SUCCESS = 'SEND_RAVEN_NODE_LINK_SUCCESS';
export const SEND_RAVEN_NODE_LINK_FAILURE = 'SEND_RAVEN_NODE_LINK_FAILURE';

// Meta Data and Tickets
export const FETCH_RAVEN_TICKET_REQUEST = 'FETCH_RAVEN_TICKET_REQUEST';
export const FETCH_RAVEN_TICKET_SUCCESS = 'FETCH_RAVEN_TICKET_SUCCESS';
export const FETCH_RAVEN_TICKET_FAILURE = 'FETCH_RAVEN_TICKET_FAILURE';

// Meta Data and Tickets
export const FETCH_RAVEN_METADATA_REQUEST = 'FETCH_RAVEN_METADATA_REQUEST';
export const FETCH_RAVEN_METADATA_SUCCESS = 'FETCH_RAVEN_METADATA_SUCCESS';
export const FETCH_RAVEN_METADATA_FAILURE = 'FETCH_RAVEN_METADATA_FAILURE';
