export const FETCH_SMS_EVENTS_REQUEST = 'FETCH_SMS_EVENTS_REQUEST';
export const FETCH_SMS_EVENTS_SUCCESS = 'FETCH_SMS_EVENTS_SUCCESS';
export const FETCH_SMS_EVENTS_FAILURE = 'FETCH_SMS_EVENTS_FAILURE';

export const FETCH_EMAIL_EVENTS_REQUEST = 'FETCH_EMAIL_EVENTS_REQUEST';
export const FETCH_EMAIL_EVENTS_SUCCESS = 'FETCH_EMAIL_EVENTS_SUCCESS';
export const FETCH_EMAIL_EVENTS_FAILURE = 'FETCH_EMAIL_EVENTS_FAILURE';

export const FETCH_WHATS_APP_EVENTS_REQUEST = 'FETCH_WHATS_APP_EVENTS_REQUEST';
export const FETCH_WHATS_APP_EVENTS_SUCCESS = 'FETCH_WHATS_APP_EVENTS_SUCCESS';
export const FETCH_WHATS_APP_EVENTS_FAILURE = 'FETCH_WHATS_APP_EVENTS_FAILURE';

export const FETCH_PUSH_NOTIFICATION_EVENTS_REQUEST =
  'FETCH_PUSH_NOTIFICATION_EVENTS_REQUEST';
export const FETCH_PUSH_NOTIFICATION_EVENTS_SUCCESS =
  'FETCH_PUSH_NOTIFICATION_EVENTS_SUCCESS';
export const FETCH_PUSH_NOTIFICATION_EVENTS_FAILURE =
  'FETCH_PUSH_NOTIFICATION_EVENTS_FAILURE';

export const FETCH_EMAIL_EVENT_REQUEST = 'FETCH_EMAIL_EVENT_REQUEST';
export const FETCH_EMAIL_EVENT_SUCCESS = 'FETCH_EMAIL_EVENT_SUCCESS';
export const FETCH_EMAIL_EVENT_FAILURE = 'FETCH_EMAIL_EVENT_FAILURE';

export const FETCH_EMAIL_ID_TEMPLATES_REQUEST =
  'FETCH_EMAIL_ID_TEMPLATES_REQUEST';
export const FETCH_EMAIL_ID_TEMPLATES_SUCCESS =
  'FETCH_EMAIL_ID_TEMPLATES_SUCCESS';
export const FETCH_EMAIL_ID_TEMPLATES_FAILURE =
  'FETCH_EMAIL_ID_TEMPLATES_FAILURE';

export const FETCH_SMS_TEMPLATES_SUCCESS = 'FETCH_SMS_TEMPLATES_SUCCESS';
export const FETCH_SMS_TEMPLATES_FAILURE = 'FETCH_SMS_TEMPLATES_FAILURE';
export const FETCH_WHATSAPP_TEMPLATES_SUCCESS =
  'FETCH_WHATSAPP_TEMPLATES_SUCCESS';
export const FETCH_WHATSAPP_TEMPLATES_FAILURE =
  'FETCH_WHATSAPP_TEMPLATES_FAILURE';
export const FETCH_PUSH_NOTIFICATION_TEMPLATES_SUCCESS =
  'FETCH_PUSH_NOTIFICATION_TEMPLATES_SUCCESS';
export const FETCH_PUSH_NOTIFICATION_TEMPLATES_FAILURE =
  'FETCH_PUSH_NOTIFICATION_TEMPLATES_FAILURE';

export const SWITCH_CURRENT_EVENT_LOADING = 'SWITCH_CURRENT_EVENT_LOADING';
export const CLEAR_EMAIL_EVENT = 'CLEAR_EMAIL_EVENT';

export const UPDATE_SMS_EVENTS_REQUEST = 'UPDATE_SMS_EVENTS_REQUEST';
export const UPDATE_SMS_EVENTS_SUCCESS = 'UPDATE_SMS_EVENTS_SUCCESS';
export const UPDATE_SMS_EVENTS_FAILURE = 'UPDATE_SMS_EVENTS_FAILURE';

export const ADD_EVENT_TO_CURRENT_EVENT = 'ADD_EVENT_TO_CURRENT_EVENT';
export const REMOVE_EVENT_TO_CURRENT_EVENT = 'REMOVE_EVENT_TO_CURRENT_EVENT';

export const TOGGLE_ACTION_DATA_REQUEST = 'TOGGLE_ACTION_DATA_REQUEST';
export const TOGGLE_ACTION_DATA_SUCCESS = 'TOGGLE_ACTION_DATA_SUCCESS';
export const TOGGLE_ACTION_DATA_FAILURE = 'TOGGLE_ACTION_DATA_FAILURE';

export const PREVIEW_EMAIL_EVENTS_REQUEST = 'PREVIEW_EMAIL_EVENTS_REQUEST';
export const PREVIEW_EMAIL_EVENTS_SUCCESS = 'PREVIEW_EMAIL_EVENTS_SUCCESS';
export const PREVIEW_EMAIL_EVENTS_FAILURE = 'PREVIEW_EMAIL_EVENTS_FAILURE';

export const PREVIEW_SMS_EVENTS_REQUEST = 'PREVIEW_SMS_EVENTS_REQUEST';
export const PREVIEW_SMS_EVENTS_SUCCESS = 'PREVIEW_SMS_EVENTS_SUCCESS';
export const PREVIEW_SMS_EVENTS_FAILURE = 'PREVIEW_SMS_EVENTS_FAILURE';

export const PREVIEW_PUSH_NOTIFICATION_EVENTS_REQUEST =
  'PREVIEW_PUSH_NOTIFICATION_EVENTS_REQUEST';
export const PREVIEW_PUSH_NOTIFICATION_EVENTS_SUCCESS =
  'PREVIEW_PUSH_NOTIFICATION_EVENTS_SUCCESS';
export const PREVIEW_PUSH_NOTIFICATION_EVENTS_FAILURE =
  'PREVIEW_PUSH_NOTIFICATION_EVENTS_FAILURE';

export const PREVIEW_EMAIL_TEMPLATE_REQUEST = 'PREVIEW_EMAIL_TEMPLATE_REQUEST';
export const PREVIEW_EMAIL_TEMPLATE_SUCCESS = 'PREVIEW_EMAIL_TEMPLATE_SUCCESS';
export const PREVIEW_EMAIL_TEMPLATE_FAILURE = 'PREVIEW_EMAIL_TEMPLATE_FAILURE';

export const UPDATE_EMAIL_EVENTS_REQUEST = 'UPDATE_EMAIL_EVENTS_REQUEST';
export const UPDATE_EMAIL_EVENTS_SUCCESS = 'UPDATE_EMAIL_EVENTS_SUCCESS';
export const UPDATE_EMAIL_EVENTS_FAILURE = 'UPDATE_EMAIL_EVENTS_FAILURE';

export const UPDATE_WHATS_APP_EVENTS_REQUEST =
  'UPDATE_WHATS_APP_EVENTS_REQUEST';
export const UPDATE_WHATS_APP_EVENTS_SUCCESS =
  'UPDATE_WHATS_APP_EVENTS_SUCCESS';
export const UPDATE_WHATS_APP_EVENTS_FAILURE =
  'UPDATE_WHATS_APP_EVENTS_FAILURE';

export const UPDATE_PUSH_NOTIFICATION_EVENTS_REQUEST =
  'UPDATE_PUSH_NOTIFICATION_EVENTS_REQUEST';
export const UPDATE_PUSH_NOTIFICATION_EVENTS_SUCCESS =
  'UPDATE_PUSH_NOTIFICATION_EVENTS_SUCCESS';
export const UPDATE_PUSH_NOTIFICATION_EVENTS_FAILURE =
  'UPDATE_PUSH_NOTIFICATION_EVENTS_FAILURE';

/* Raven APP */

// FETCH Root Nodes Constant
export const CREATE_RAVEN_NODE_REQUEST = 'CREATE_RAVEN_NODE_REQUEST';
export const CREATE_RAVEN_NODE_SUCCESS = 'CREATE_RAVEN_NODE_SUCCESS';
export const CREATE_RAVEN_NODE_FAILURE = 'CREATE_RAVEN_NODE_FAILURE';

export const FETCH_RAVEN_ROOT_NODES_REQUEST = 'FETCH_RAVEN_ROOT_NODES_REQUEST';
export const FETCH_RAVEN_ROOT_NODES_SUCCESS = 'FETCH_RAVEN_ROOT_NODES_SUCCESS';
export const FETCH_RAVEN_ROOT_NODES_FAILURE = 'FETCH_RAVEN_ROOT_NODES_FAILURE';

export const ASSIGN_ROOT_NODE_DETAILS = 'ASSIGN_ROOT_NODE_DETAILS';

export const UPDATE_RAVEN_NODE_REQUEST = 'UPDATE_RAVEN_NODE_REQUEST';
export const UPDATE_RAVEN_NODE_SUCCESS = 'UPDATE_RAVEN_NODE_SUCCESS';
export const UPDATE_RAVEN_NODE_FAILURE = 'UPDATE_RAVEN_NODE_FAILURE';

export const UPDATE_RAVEN_NODE_RANK_REQUEST = 'UPDATE_RAVEN_NODE_RANK_REQUEST';
export const UPDATE_RAVEN_NODE_RANK_SUCCESS = 'UPDATE_RAVEN_NODE_RANK_SUCCESS';
export const UPDATE_RAVEN_NODE_RANK_FAILURE = 'UPDATE_RAVEN_NODE_RANK_FAILURE';
export const UPDATE_CHANGE_NODE_RANK = 'UPDATE_CHANGE_NODE_RANK';
export const SET_CURRENT_NODE_KEY = 'SET_CURRENT_NODE_KEY';

export const FETCH_LINKED_RAVEN_NODE_REQUEST =
  'FETCH_LINKED_RAVEN_NODE_REQUEST';
export const FETCH_LINKED_RAVEN_NODE_SUCCESS =
  'FETCH_LINKED_RAVEN_NODE_SUCCESS';
export const FETCH_LINKED_RAVEN_NODE_FAILURE =
  'FETCH_LINKED_RAVEN_NODE_FAILURE';

// ADD Root Nodes Constants
export const ADD_RAVEN_NODE_REQUEST = 'ADD_RAVEN_NODE_REQUEST';
export const ADD_RAVEN_NODE_SUCCESS = 'ADD_RAVEN_NODE_SUCCESS';
export const ADD_RAVEN_NODE_FAILURE = 'ADD_RAVEN_NODE_FAILURE';

// ADD Root Nodes Constants
export const ADD_RAVEN_NODE_ACTION_REQUEST = 'ADD_RAVEN_NODE_ACTION_REQUEST';
export const ADD_RAVEN_NODE_ACTION_SUCCESS = 'ADD_RAVEN_NODE_ACTION_SUCCESS';
export const ADD_RAVEN_NODE_ACTION_FAILURE = 'ADD_RAVEN_NODE_ACTION_FAILURE';

// ADD Root Nodes Constants
export const CHANGE_RAVEN_NODE_ACTION_REQUEST =
  'CHANGE_RAVEN_NODE_ACTION_REQUEST';
export const CHANGE_RAVEN_NODE_ACTION_SUCCESS =
  'CHANGE_RAVEN_NODE_ACTION_SUCCESS';
export const CHANGE_RAVEN_NODE_ACTION_FAILURE =
  'CHANGE_RAVEN_NODE_ACTION_FAILURE';

export const FETCH_RAVEN_INACTIVE_NODE_LINKS_REQUEST =
  'FETCH_RAVEN_INACTIVE_NODE_LINKS_REQUEST';
export const FETCH_RAVEN_INACTIVE_NODE_LINKS_SUCCESS =
  'FETCH_RAVEN_INACTIVE_NODE_LINKS_SUCCESS';
export const FETCH_RAVEN_INACTIVE_NODE_LINKS_FAILURE =
  'FETCH_RAVEN_INACTIVE_NODE_LINKS_FAILURE';

// FETCH Nodes Constants
export const FETCH_RAVEN_NODES_REQUEST = 'FETCH_RAVEN_NODES_REQUEST';
export const FETCH_RAVEN_NODES_SUCCESS = 'FETCH_RAVEN_NODES_SUCCESS';
export const FETCH_RAVEN_NODES_FAILURE = 'FETCH_RAVEN_NODES_FAILURE';

// FETCH Root Actions Constants
export const FETCH_RAVEN_ACTIONS_NODES_REQUEST =
  'FETCH_RAVEN_ACTIONS_NODES_REQUEST';
export const FETCH_RAVEN_ACTIONS_NODES_SUCCESS =
  'FETCH_RAVEN_ACTIONS_NODES_SUCCESS';
export const FETCH_RAVEN_ACTIONS_NODES_FAILURE =
  'FETCH_RAVEN_ACTIONS_NODES_FAILURE';

// FETCH Root Nodes Constants
export const SEND_RAVEN_NODE_LINK_REQUEST = 'SEND_RAVEN_NODE_LINK_REQUEST';
export const SEND_RAVEN_NODE_LINK_SUCCESS = 'SEND_RAVEN_NODE_LINK_SUCCESS';
export const SEND_RAVEN_NODE_LINK_FAILURE = 'SEND_RAVEN_NODE_LINK_FAILURE';

// Meta Data and Tickets
export const FETCH_RAVEN_TICKET_REQUEST = 'FETCH_RAVEN_TICKET_REQUEST';
export const FETCH_RAVEN_TICKET_SUCCESS = 'FETCH_RAVEN_TICKET_SUCCESS';
export const FETCH_RAVEN_TICKET_FAILURE = 'FETCH_RAVEN_TICKET_FAILURE';

// Meta Data and Tickets
export const FETCH_RAVEN_METADATA_REQUEST = 'FETCH_RAVEN_METADATA_REQUEST';
export const FETCH_RAVEN_METADATA_SUCCESS = 'FETCH_RAVEN_METADATA_SUCCESS';
export const FETCH_RAVEN_METADATA_FAILURE = 'FETCH_RAVEN_METADATA_FAILURE';

// Create New Event
export const FETCH_CREATE_EVENT_FORM_STRUCTURE_REQUEST =
  'FETCH_CREATE_EVENT_FORM_STRUCTURE_REQUEST';
export const FETCH_CREATE_EVENT_FORM_STRUCTURE_SUCCESS =
  'FETCH_CREATE_EVENT_FORM_STRUCTURE_SUCCESS';
export const FETCH_CREATE_EVENT_FORM_STRUCTURE_FAILURE =
  'FETCH_CREATE_EVENT_FORM_STRUCTURE_FAILURE';
export const CREATE_NEW_EVENT_REQUEST = 'CREATE_NEW_EVENT_REQUEST';
export const CREATE_NEW_EVENT_SUCCESS = 'CREATE_NEW_EVENT_SUCCESS';
export const CREATE_NEW_EVENT_FAILURE = 'CREATE_NEW_EVENT_FAILURE';
export const CREATE_APP_REQUEST = 'CREATE_APP_REQUEST';
export const CREATE_APP_SUCCESS = 'CREATE_APP_SUCCESS';
export const CREATE_APP_FAILURE = 'CREATE_APP_FAILURE';

// Home page data events
export const FETCH_HOME_DATA_REQUEST = 'FETCH_HOME_DATA_REQUEST';
export const FETCH_HOME_DATA_SUCCESS = 'FETCH_HOME_DATA_SUCCESS';
export const FETCH_HOME_DATA_FAILURE = 'FETCH_HOME_DATA_FAILURE';

// Providers page data events
export const FETCH_PROVIDERS_LIST_REQUEST = 'FETCH_PROVIDERS_LIST_REQUEST';
export const FETCH_PROVIDERS_LIST_SUCCESS = 'FETCH_PROVIDERS_LIST_SUCCESS';
export const FETCH_PROVIDERS_LIST_FAILURE = 'FETCH_PROVIDERS_LIST_FAILURE';

export const FETCH_ADD_PROVIDERS_LIST_SUCCESS =
  'FETCH_ADD_PROVIDERS_LIST_SUCCESS';
export const FETCH_ADD_PROVIDERS_LIST_REQUEST =
  'FETCH_ADD_PROVIDERS_LIST_REQUEST';

export const FETCH_ADD_PROVIDERS_FORM_STRUCTURE_REQUEST =
  'FETCH_ADD_PROVIDERS_FORM_STRUCTURE_REQUEST';
export const FETCH_ADD_PROVIDERS_FORM_STRUCTURE_FAILURE =
  'FETCH_ADD_PROVIDERS_FORM_STRUCTURE_FAILURE';
export const FETCH_ADD_PROVIDERS_FORM_STRUCTURE_SUCCESS =
  'FETCH_ADD_PROVIDERS_FORM_STRUCTURE_SUCCESS';

export const FETCH_UPDATE_PROVIDERS_FORM_STRUCTURE_REQUEST =
  'FETCH_UPDATE_PROVIDERS_FORM_STRUCTURE_REQUEST';
export const FETCH_UPDATE_PROVIDERS_FORM_STRUCTURE_FAILURE =
  'FETCH_UPDATE_PROVIDERS_FORM_STRUCTURE_FAILURE';
export const FETCH_UPDATE_PROVIDERS_FORM_STRUCTURE_SUCCESS =
  'FETCH_UPDATE_PROVIDERS_FORM_STRUCTURE_SUCCESS';

export const RESET_PROVIDERS_FORM = 'RESET_PROVIDERS_FORM';

export const ADD_PROVIDER_REQUEST = 'ADD_PROVIDER_REQUEST';
export const ADD_PROVIDER_FAILURE = 'ADD_PROVIDER_FAILURE';

// Tenants page data events
export const FETCH_APPS_LIST_REQUEST = 'FETCH_APPS_LIST_REQUEST';
export const FETCH_APPS_LIST_SUCCESS = 'FETCH_APPS_LIST_SUCCESS';
export const FETCH_APPS_LIST_FAILURE = 'FETCH_APPS_LIST_FAILURE';
export const FETCH_EDIT_APP_FORM_REQUEST = 'FETCH_EDIT_APP_FORM_REQUEST';
export const FETCH_EDIT_APP_FORM_SUCCESS = 'FETCH_EDIT_APP_FORM_SUCCESS';
export const FETCH_EDIT_APP_FORM_FAILURE = 'FETCH_EDIT_APP_FORM_FAILURE';

export const UPDATE_APP_REQUEST = 'UPDATE_APP_REQUEST';
export const UPDATE_APP_SUCCESS = 'UPDATE_APP_SUCCESS';
export const UPDATE_APP_FAILURE = 'UPDATE_APP_FAILURE';

// Activity feed data events
export const FETCH_ACTIVITY_FEED_REQUEST = 'FETCH_ACTIVITY_FEED_REQUEST';
export const FETCH_ACTIVITY_FEED_SUCCESS = 'FETCH_ACTIVITY_FEED_SUCCESS';
export const FETCH_ACTIVITY_FEED_FAILURE = 'FETCH_ACTIVITY_FEED_FAILURE';

// Settings page data events
export const FETCH_DEFAULT_PRIORITY_REQUEST = 'FETCH_DEFAULT_PRIORITY_REQUEST';
export const FETCH_DEFAULT_PRIORITY_SUCCESS = 'FETCH_DEFAULT_PRIORITY_SUCCESS';
export const FETCH_DEFAULT_PRIORITY_FAILURE = 'FETCH_DEFAULT_PRIORITY_FAILURE';

export const SET_DEFAULT_PRIORITY_REQUEST = 'SET_DEFAULT_PRIORITY_REQUEST';
export const SET_DEFAULT_PRIORITY_SUCCESS = 'SET_DEFAULT_PRIORITY_SUCCESS';
export const SET_DEFAULT_PRIORITY_FAILURE = 'SET_DEFAULT_PRIORITY_FAILURE';

export const FETCH_DYNAMIC_PRIORITY_REQUEST = 'FETCH_DYNAMIC_PRIORITY_REQUEST';
export const FETCH_DYNAMIC_PRIORITY_SUCCESS = 'FETCH_DYNAMIC_PRIORITY_SUCCESS';
export const FETCH_DYNAMIC_PRIORITY_FAILURE = 'FETCH_DYNAMIC_PRIORITY_FAILURE';

export const SET_DYNAMIC_PRIORITY_REQUEST = 'SET_DYNAMIC_PRIORITY_REQUEST';
export const SET_DYNAMIC_PRIORITY_SUCCESS = 'SET_DYNAMIC_PRIORITY_SUCCESS';
export const SET_DYNAMIC_PRIORITY_FAILURE = 'SET_DYNAMIC_PRIORITY_FAILURE';
